version: 2

jobs:
  "Execute tests on macOS (Xcode 9.0.1, Ruby 2.3)":
    macos:
      xcode: "9.0.1"
    environment:
      CIRCLE_TEST_REPORTS: ~/test-reports
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

      - restore_cache:
          key: v1-macos-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
      - restore_cache:
          keys:
            - v3-homebrew-{{ epoch }}
            - v3-homebrew
      - run:
          name: Setup Build
          command: |
            mkdir -p ~/test-reports
            echo "2.3" > .ruby-version
            brew untap caskroom/versions
            brew install shellcheck
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle

      - save_cache:
          key: v3-homebrew-{{ epoch }}
          paths:
            - /usr/local/Homebrew
      - save_cache:
          key: v1-macos-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
          paths:
            - .bundle

      - run:
          name: Check PR Metadata
          command: bundle exec danger || echo "danger failed"

      - restore_cache:
          key: v1-{{ arch }}-rubocop

      - run: bundle exec fastlane execute_tests

      - save_cache:
          key: v1-{{ arch }}-rubocop
          paths:
            - ~/.cache/rubocop_cache
      - store_test_results:
          path: ~/test-reports
      - store_artifacts:
          path: ~/test-reports/rspec
          destination: test-reports

      - run:
          name: Post Test Results to GitHub
          command: bundle exec danger || echo "danger failed"
          when: always # Run this even when tests fail

  "Execute tests on macOS (Xcode 11.0.0, Ruby 2.5)":
    macos:
      xcode: "11.0.0"
    environment:
      CIRCLE_TEST_REPORTS: ~/test-reports
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

      - restore_cache:
          key: v1-macos-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
      - restore_cache:
          keys:
            - v3-homebrew-{{ epoch }}
            - v3-homebrew
      - run:
          name: Setup Build
          command: |
            mkdir -p ~/test-reports
            echo "2.5" > .ruby-version
            brew untap caskroom/versions
            brew install shellcheck
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle

      - save_cache:
          key: v3-homebrew-{{ epoch }}
          paths:
            - /usr/local/Homebrew
      - save_cache:
          key: v1-macos-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
          paths:
            - .bundle

      - run:
          name: Check PR Metadata
          command: bundle exec danger || echo "danger failed"

      - restore_cache:
          key: v1-{{ arch }}-rubocop

      - run: bundle exec fastlane execute_tests

      - save_cache:
          key: v1-{{ arch }}-rubocop
          paths:
            - ~/.cache/rubocop_cache
      - store_test_results:
          path: ~/test-reports
      - store_artifacts:
          path: ~/test-reports/rspec
          destination: test-reports

      - run:
          name: Post Test Results to GitHub
          command: bundle exec danger || echo "danger failed"
          when: always # Run this even when tests fail

  "Execute tests on Ubuntu":
    environment:
      CIRCLE_TEST_REPORTS: ~/test-reports
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      FASTLANE_ITUNES_TRANSPORTER_PATH: .bundle
    docker:
      - image: fastlanetools/ci:0.1.0
    steps:
      - checkout

      - restore_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
      - run:
          name: Setup Build
          command: |
            mkdir -p ~/test-reports
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle
      - save_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
          paths:
            - .bundle

      - run:
          name: Check PR Metadata
          command: bundle exec danger || echo "danger failed"

      - restore_cache:
          key: v1-{{ arch }}-rubocop

      - run: bundle exec fastlane execute_tests

      - save_cache:
          key: v1-{{ arch }}-rubocop
          paths:
            - ~/.cache/rubocop_cache
      - store_test_results:
          path: ~/test-reports
      - store_artifacts:
          path: ~/test-reports/rspec
          destination: test-reports

      - run:
          name: Post Test Results to GitHub
          command: bundle exec danger || echo "danger failed"
          when: always # Run this even when tests fail

  "Validate Fastlane.swift Generation":
    macos:
      xcode: "11.0.0"
    environment:
      CIRCLE_TEST_REPORTS: ~/test-reports
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

      - restore_cache:
          key: v1-macos-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
      - restore_cache:
          keys:
            - v3-homebrew-{{ epoch }}
            - v3-homebrew
      - run:
          name: Setup Build
          command: |
            mkdir -p ~/test-reports
            echo "2.5" > .ruby-version
            brew untap caskroom/versions
            brew install shellcheck
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle

      - save_cache:
          key: v3-homebrew-{{ epoch }}
          paths:
            - /usr/local/Homebrew
      - save_cache:
          key: v1-macos-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
          paths:
            - .bundle

      - run: bundle exec fastlane generate_swift_api

  "Validate Documentation":
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout

      - restore_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}
      - run:
          name: Setup Build
          command: |
            gem update --system
            gem install bundler
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle
      - save_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}
          paths:
            - .bundle

      - run: bundle exec fastlane validate_docs

  "Lint Source Code":
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout

      - restore_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}
      - run:
          name: Setup Build
          command: |
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle
      - save_cache:
          key: v1-ubuntu-gems-{{ checksum "Gemfile" }}
          paths:
            - .bundle

      - run: bundle exec fastlane lint_source

  "Execute modules load up tests":
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    docker:
      - image: circleci/ruby:2.3
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

      - run:
          name: Setup Build
          # Build gem from fastlane.gemspec and install locally
          command: |
            gem install $(echo $(gem build fastlane.gemspec) | sed 's/.*File: //')

      - run: /bin/bash ./test_modules/run_tests.sh

workflows:
  version: 2
  build:
    jobs:
      - "Execute tests on macOS (Xcode 9.0.1, Ruby 2.3)"
      - "Execute tests on macOS (Xcode 11.0.0, Ruby 2.5)"
      - "Execute tests on Ubuntu"
      - "Validate Fastlane.swift Generation"
      - "Validate Documentation"
      - "Lint Source Code"
      - "Execute modules load up tests"
